// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAcnOwnbRGtPuK7aAWBbwKcLXpSlJ1e_w',
    appId: '1:193142558349:web:1fd97e96f5a02186875cc4',
    messagingSenderId: '193142558349',
    projectId: 'electric-home-7e630',
    authDomain: 'electric-home-7e630.firebaseapp.com',
    storageBucket: 'electric-home-7e630.firebasestorage.app',
    measurementId: 'G-3QX3RTN24Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzr9V-XcaTglUVCQDBq-yDAgiunUDXTBU',
    appId: '1:193142558349:android:8e88ce6204e48906875cc4',
    messagingSenderId: '193142558349',
    projectId: 'electric-home-7e630',
    storageBucket: 'electric-home-7e630.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkeTqbHyKwVNROc5_fy_Rjwo8SwIq4Onc',
    appId: '1:193142558349:ios:3944ec62f649dc16875cc4',
    messagingSenderId: '193142558349',
    projectId: 'electric-home-7e630',
    storageBucket: 'electric-home-7e630.firebasestorage.app',
    iosBundleId: 'com.example.electricHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkeTqbHyKwVNROc5_fy_Rjwo8SwIq4Onc',
    appId: '1:193142558349:ios:3944ec62f649dc16875cc4',
    messagingSenderId: '193142558349',
    projectId: 'electric-home-7e630',
    storageBucket: 'electric-home-7e630.firebasestorage.app',
    iosBundleId: 'com.example.electricHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAcnOwnbRGtPuK7aAWBbwKcLXpSlJ1e_w',
    appId: '1:193142558349:web:ca70e418b912e937875cc4',
    messagingSenderId: '193142558349',
    projectId: 'electric-home-7e630',
    authDomain: 'electric-home-7e630.firebaseapp.com',
    storageBucket: 'electric-home-7e630.firebasestorage.app',
    measurementId: 'G-J6CY178D5B',
  );

}