/// Flutter icons MyFlutterApp
/// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData computer = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plug = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData light = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fan = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faucet = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bathtub = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData washing_machine = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData electrical = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shower = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
